apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        name: azure-vote-back
        ports:
        - containerPort: 6379
          name: redis
      nodeSelector:
        beta.kubernetes.io/os: linux

---

apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
      - env:
        - name: REDIS
          value: azure-vote-back
        image:
        name: azure-vote-front
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
      nodeSelector:
        beta.kubernetes.io/os: linux

---

apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  ports:
  - port: 80
  selector:
    app: azure-vote-front
  type: LoadBalancer
